platform :ios, '8.0'
use_frameworks!

target 'YTKNetworkDemo' do
    pod 'YTKNetwork', :path => '../'
    pod 'AFNetworking'
end

target 'YTKNetworkDemoTests' do
    pod 'YTKNetwork', :path => '../'
end

